<div class="clearfix"></div>
<?php
$form = $this->form;
$form->prepare();
$hiddenInfoRegistro = '';
$action = $form->getAttribute('action');
if ($action == 'add' || $action == 'buscar') {
    $hiddenInfoRegistro = 'hidden';
}
echo $this->form()->openTag($form);
?>
<fieldset>
    <legend>Informacion del Centro Poblado</legend>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="pk_departamento_id">Departamento <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('pk_departamento_id')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="pk_municipio_id">Municipio <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('pk_municipio_id')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="centropoblado">Centro Poblado <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('centropoblado')); ?>
        </div>
    </div>
</fieldset>
<?php
if ($action == 'buscar') {
    echo "<div hidden>";
}
?>
<div class="ln_solid"></div>
<div class="form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
        <?php
        if ($action != 'buscar') {
            echo $this->formRow($form->get('btnCancelar'));
            if ($action != 'detail') {
                if ($action == 'delete') {
                    echo $this->formSubmit($form->get('btnEnviar')->setValue('Eliminar'));
                } else {
                    echo $this->formSubmit($form->get('btnEnviar'));
                }
            }
        }
        ?>
    </div>
</div>
<?php
if ($action == 'buscar') {
    echo "</div>";
}
?>
<?php echo $this->form()->closeTag(); ?>
