<!-- footer content -->
<footer>
    <div class="row">
        <div class="col-xs-6 col-md-6" style="text-align: left">
            
        </div>
        <div class="col-xs-6 col-md-6" style="text-align: right">
            <b>GIMNASIO GYM-JAM S.A.S.</b><br>
            &copy; Copyright <?php echo date('Y') ?>
        </div>
    </div>
    <div class="clearfix"></div>
</footer>
<!-- /footer content -->
