<?php
if (defined('RUNNING_FROM_ROOT')) {
    $this->plugin('basePath')->setBasePath($this->basePath() . '/public');
}
echo $this->doctype();
?>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <?php
        echo $this->headTitle('GIMNASIO :: ' . $this->translate('Gimnasio Gym-Jam'))->setSeparator(' - ')->setAutoEscape(false);
        echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/custom.css'))
                ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'));
        echo $this->headScript()
                ->prependFile($this->basePath('js/sistema/usuario.js'))
                ->prependFile($this->basePath('js/jquery.smartWizard.js'))
                ->prependFile($this->basePath('js/nprogress.js'))
                ->prependFile($this->basePath('js/fastclick.js'))
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',));
        ?>
        <script>
            function apagarServidor() {
                if (confirm("ESTA A PUNTO DE APAGAR EL SERVIDOR DE JOSANDRO !!! \n\nRECUERDE QUE UNA VEZ APAGADO NO SERA POSIBLE ENCENDERLO VIA WEB Y POR LO TANTO USTED TENDRA QUE ENCENDERLO MANUALMENTE. \n\nDESEA CONTINUAR CON EL APAGADO DEL SERVIDOR ?")) {
                    $.ajax({
                        url: "/josandro/configuracion/servidor/apagar",
                    }).done(function (datos) {
                        if (parseInt(datos['ok']) === 1) {
                            alert("EL SERVIDOR HA INICIADO EL PROCESO DE APAGADO. \nESTA SESION DE USUARIO SERA CERRADA EN POCOS SEGUNDOS");
                        } else {
                            alert("[ERROR] EL PROCESO DE APAGO DEL SERVIDOR NO FUE INICIADO")
                        }
                    });
                }
                return false;
            }
        </script>
    </head>
    <body class="nav-md">
        <div class="container body">
            <div class="main_container">
                <?php echo $this->header; ?>
                <?php echo $this->menu; ?>
                <div class="right_col" role="main">
                    <br />
                    <?php echo $this->content; ?>
                </div>
                <?php echo $this->footer; ?>
            </div>
        </div>
        <script src="/josandro/public/js/custom.js?23Enero2020"></script>
    </body>
</html>
