<?php
$nombreUsuario = 'SESION NO INICIADA';
$rol = 'Administrador';
if ($sesionUsuario = $this->identity()) {
    $nombreUsuario = $this->escapeHtml($sesionUsuario->nombresapellidos);
    $sexo = $this->escapeHtml($sesionUsuario->sexo);
    $rol = $this->escapeHtml($sesionUsuario->rol);
    if ($sexo == 'Masculino') {
        $ao = 'o';
    } else {
        $ao = 'a';
    }
}
?>
<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <img src="" style="width: 80%" alt=""/> <br><br>
        </div>
        <div class="profile"><!--img_2 -->
            <div class="profile_pic">
                <?php
                if ($sexo == 'Masculino') {
                    echo '<img src="/gimnasio/public/img/gimnasio.png" alt="" class="img-circle profile_img">';
                } else {
                    echo '<img src="/gimnasio/public/img/gimnasio.png" alt="" class="img-circle profile_img">';
                }
                ?>
            </div>
            <div class="profile_info">
                <span>BIENVENIDO</span>
                <h2><?php echo $nombreUsuario; ?></h2> <br>
               
            </div>
        </div>
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <h3>Menú General</h3>
                <ul class="nav side-menu">
                    <li>
                        <a href="<?php echo $this->url('inicio', array('controller' => 'bandejaentrada', 'action' => 'index')) ?>" style="color: #fafafa"><i class="fa fa-home"></i> INICIO</a>
                    </li>
                     
                    <li><a><i class="fa fa-user" style="color: #fafafa"></i> GIMNASIO<span class="fa fa-chevron-down" style="color: #fafafa"></span></a>
                        <ul class="nav child_menu">
                            <li class="sub_menu"><a href="<?php echo $this->url('finanzas/default', array('controller' => 'asistencia', 'action' => 'index')) ?>"> ASISTENCIA DE CLIENTES</a></li>
                            <li class="sub_menu"><a href="<?php echo $this->url('finanzas/default', array('controller' => 'cajaspersonales', 'action' => 'index')) ?>"> REGISTRO DE CLIENTES</a></li>
                            <li class="sub_menu"><a href="<?php echo $this->url('finanzas/default', array('controller' => 'productos', 'action' => 'index')) ?>"> VENTA DE PRODUCTOS</a></li>
                            
                        </ul>
                    </li>
                    
                    <li><a><i class=" fa fa-shopping-basket" style="color: #fafafa"></i> INVENTARIO<span class="fa fa-chevron-down" style="color: #fafafa"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="<?php echo $this->url('registro/default', array('controller' => 'registro', 'action' => 'index')) ?>"> REGISTRO DE MATERIALES</a></li>                      
                            <li><a href="<?php echo $this->url('producto/default', array('controller' => 'producto', 'action' => 'index')) ?>"> REGISTRO DE PRODUCTOS</a></li>
                        </ul>
                    </li> 
                   
                        <li><a><i class="fa fa-address-card " style="color: #fafafa"></i> TALENTO HUMANO<span class="fa fa-chevron-down" style="color: #fafafa"></span></a>
                             
                            <ul class="nav child_menu">
                                <li class="sub_menu"><a href="<?php echo $this->url('talentohumano/default', array('controller' => 'empleado', 'action' => 'index')) ?>"> EMPLEADOS</a></li>
                                <li class="sub_menu"><a href="<?php echo $this->url('talentohumano/default', array('controller' => 'contrato-laboral', 'action' => 'index')) ?>"> CONTRATOS LABORALES</a></li>                              
                            </ul>
                             
                        </li>      
                       
                    </ul>
                </div>
            </div>

            <div class="sidebar-footer hidden-small">
                <a data-toggle="tooltip" data-placement="top" title="Configuracion" style="color: #fafafa">
                    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                </a>
                <a data-toggle="tooltip" data-placement="top" title="Pantalla Completa" style="color: #fafafa">
                    <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                </a>
                <a data-toggle="tooltip" data-placement="top" title="Bloquear" style="color: #fafafa">
                    <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                </a>
                <a href="<?php echo $this->url('login/default', array('controller' => 'login', 'action' => 'cerrarSesion')) ?>" data-toggle="tooltip" data-placement="top" title="Salir" style="color: #fafafa">
                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                </a>
            </div>
        </div>
    </div>
