<?php
$nombreUsuario = 'SESION NO INICIADA';
if ($sesionUsuario = $this->identity()) {
    $nombreUsuario = $this->escapeHtml($sesionUsuario->nombresapellidos);
    $sexo = $this->escapeHtml($sesionUsuario->sexo);
    if ($sexo == 'Masculino') {
        $ao = 'o';
    } else {
        $ao = 'a';
    }
}
?>
<div class="col-md-3 left_col">
    <div class="left_col scroll-view">

        <div class="navbar nav_title" style="border: 0;">
            <img src="/gimnasio/public/img/gimnasio.png" style="width: 80%" alt="Josandro - Gimnasio Gym-Jam S.A.S."/> <br><br>
        </div>

        <div class="profile"><!--img_2 -->
            <div class="profile_pic">
                <?php
                if ($sexo == 'Masculino') {
                    echo '<img src="//gimnasio/public/img/gimnasio.png" alt="" class="img-circle profile_img">';
                } else {
                    echo '<img src="/josandro/public/img/perfil_F.png" alt="" class="img-circle profile_img">';
                }
                ?>
            </div>
            <div class="profile_info">
                <span>Bienvenid<?php echo $ao; ?>,</span>
                <h2><?php echo $nombreUsuario; ?></h2> <br>
                <a href="<?php echo $this->url('login/default', array('controller' => 'login', 'action' => 'cerrarSesion')) ?>" class="btn btn-danger" title="CERRAR SU SESION DE USUARIO">Cerrar Sesion</a> 
            </div>
        </div>
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <h3>Menú General</h3>
                <ul class="nav side-menu">
                    <li>
                        <a href="<?php echo $this->url('inicio', array('controller' => 'bandejaentrada', 'action' => 'index')) ?>"><i class="fa fa-home"></i> Inicio</a>
                    </li>
                    <li><a><i class="fa fa-users"></i> Abonados<span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="<?php echo $this->url('abonadosinternet/default', array('controller' => 'administracion', 'action' => 'index')) ?>"> Contratos</a></li>
                            <li><a href="<?php echo $this->url('abonadosinternet/default', array('controller' => 'reportes', 'action' => 'exportar')) ?>"> Datos Abonado</a></li>
                            <li><a href="<?php echo $this->url('abonadosinternet/default', array('controller' => 'reportes', 'action' => 'exportar')) ?>"> Hist Deudas y Pagos</a></li>
                            <li><a href="<?php echo $this->url('abonadosinternet/default', array('controller' => 'reportes', 'action' => 'exportar')) ?>"> Reimpresion Factura</a></li>
                            <li><a href="<?php echo $this->url('abonadosinternet/default', array('controller' => 'reportes', 'action' => 'exportar')) ?>"> Mapa de Abonados</a></li>
                        </ul>
                    </li> 
                    <li>
                        <a href="<?php echo $this->url('personas/default', array('controller' => 'administracion', 'action' => 'index')) ?>"><i class="fa fa-users"></i> Personas</a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-institution"></i> Empresas</a>
                    </li>
                    <li><a><i class="fa fa-internet-explorer"></i> Internet<span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="<?php echo $this->url('abonadosinternet/default', array('controller' => 'administracion', 'action' => 'index')) ?>"> Abonados</a></li>
                            <li><a href="<?php echo $this->url('abonadosinternet/default', array('controller' => 'reportes', 'action' => 'exportar')) ?>"> Reportes</a></li>
                        </ul>
                    </li> 
                    <li><a><i class="fa fa-bolt"></i> Instalaciones <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="<?php echo $this->url('instalaciones/default', array('controller' => 'administracion', 'action' => 'internet')) ?>"> Internet</a></li>
                            <li><a href="#"> Television</a></li>
                        </ul>
                    </li> 
                    <li><a><i class="fa fa-wrench"></i> Ordenes de Trabajo <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="<?php echo $this->url('ordenestrabajo/default', array('controller' => 'administracion', 'action' => 'internet')) ?>"> Internet</a></li>
                            <li><a href="#"> Television</a></li>
                        </ul>
                    </li> 
                    <li><a><i class="fa fa-file-text"></i> Facturas Internet<span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="<?php echo $this->url('facturas/default', array('controller' => 'internet', 'action' => 'personas')) ?>"> Personas</a></li>
                            <li><a href="#"> Empresas</a></li>
                            <li><a href="<?php echo $this->url('facturas/default', array('controller' => 'internet', 'action' => 'generarmensualidades')) ?>"> Generar Mensualidades</a></li>
                            <li><a href="<?php echo $this->url('facturas/default', array('controller' => 'internet', 'action' => 'generarfacturas')) ?>"> Generar Facturas</a></li>
                            <li><a href="<?php echo $this->url('facturas/default', array('controller' => 'reportes', 'action' => 'exportar')) ?>"> Reportes</a></li>
                        </ul>
                    </li> 
                    <li><a><i class="fa fa-dollar"></i> Pagos<span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="<?php echo $this->url('pagos/default', array('controller' => 'administracion', 'action' => 'registrar')) ?>"> Registrar</a></li>
                        </ul>
                    </li> 
                    <li><a><i class="fa fa-money"></i> Cajas<span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="<?php echo $this->url('cajas/default', array('controller' => 'administracion', 'action' => 'index')) ?>"> Administracion</a></li>
                            <li><a href="<?php echo $this->url('cajas/default', array('controller' => 'administracion', 'action' => 'movimientos')) ?>"> Movimientos</a></li>
                        </ul>
                    </li> 
                    <li>
                        <a href="#"><i class="fa fa-cogs"></i> Configuracion</a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Configuracion" style="color: #efc614">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Pantalla Completa" style="color: #efc614">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Bloquear" style="color: #efc614">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a href="<?php echo $this->url('login/default', array('controller' => 'login', 'action' => 'cerrarSesion')) ?>" data-toggle="tooltip" data-placement="top" title="Salir" style="color: #efc614">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
        </div>
    </div>
</div>
