<div class="clearfix"></div>
<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>

<div class="ln_solid"></div>
<fieldset>
    <legend>Informacion de Registro</legend>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="idPregunta">ID Pregunta</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('idPregunta')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="pregunta">Pregunta<span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('pregunta')); ?>
        </div>
    </div>  
</fieldset>
<div class="ln_solid"></div>
<div class="form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
        <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-close"></i> Cerrar</button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
