<div class="container body">
    <div class="main_container">
        <!-- page content -->
        <div class="col-md-12">
            <div class="col-middle">
                <div class="text-center text-center">
                    <h1 class="error-number">404</h1>
                    <h2>Lo Siento, pero no encuentro la pagina.</h2>
                    <p>La pagina que estas buscando no existe.</p> <br><br>
                    <img src="/josandro/public/img/logoJosandroFull.png" style="width: 150px" alt="Josandro - Dobleclick Software e Ingenieria S.A.S."> 
                </div>
            </div>
        </div>
    </div>
</div>
