<div class="clearfix"></div>
<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
<fieldset>
    <legend>REALIZAR VENTA DE PRODUCTO</legend>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="encargado">Encargado<span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input type="text" id="empleado" name="empleado" value="<?php echo $this->empleado; ?>" class="form-control" readonly>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="cliente">Cliente <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('cliente')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="identificacion">Identificacion<span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('identificacion')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="telefono">Teléfono Personal<span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('telefono')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="producto">Producto<span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('producto')); ?>
        </div>
    </div>
    <div id="divInfoProducto" hidden >
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="cajaTransferirA">Marca</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->formRow($form->get('marca')); ?>
            </div>
        </div>
    </div>
    
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">E-Mail<span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('email')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fechahorareg">Fecha Ingreso <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('fechahorareg')); ?>
        </div>
    </div>


    <div class="ln_solid"></div>
    <fieldset>
        <div class="ln_solid"></div>
        <legend>PAGO DE CLIENTE</legend>
        
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="costo">Costo<span class="required">*</span></label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->formRow($form->get('costo')); ?>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="pago">Pago<span class="required">*</span></label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->formRow($form->get('pago')); ?>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="ingreso">Ingreso<span class="required">*</span></label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->formRow($form->get('ingreso')); ?>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="pendiente">Pendiente<span class="required">*</span></label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->formRow($form->get('pendiente')); ?>
            </div>
        </div>

        <div hidden>
            <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="idRegistro">Id Registro <span class="required">*</span></label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <?php echo $this->formRow($form->get('idRegistro')); ?>
                </div>
            </div>
        </div>

        <div class="ln_solid"></div>
    </fieldset>

    <fieldset>
        <legend>ESTADO DE CLIENTE</legend>

        <div hidden>
            <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="idRegistro">Id Registro <span class="required">*</span></label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <?php echo $this->formRow($form->get('idRegistro')); ?>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="estado">Estado <span class="required">*</span></label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->formRow($form->get('estado')); ?>
            </div>
        </div>

        <div class="ln_solid"></div>
        <div class="form-group">
            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> REGISTRAR</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-close"></i> CERRAR</button>

            </div>
        </div>
    </fieldset>
    <?php echo $this->form()->closeTag(); ?>