<?php
$title = 'Cargos ';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath('/public/css/dataTables.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('/public/css/buttons.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('/public/css/responsive.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('/public/css/scroller.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('/public/css/green.css'));

$this->headScript()->prependScript('$(document).ready(function() {'
                . '$("#tblCargo").DataTable({'
                . 'responsive: true,'
                . '"iDisplayLength": 25,
                    "sPaginationType": "full_numbers",
                    "oLanguage": {
                        "sLengthMenu": "Mostrar: _MENU_ registros por pagina",
                        "sZeroRecords": "NO SE HA ENCONTRADO INFORMACION",
                        "sInfo": "Mostrando <b>_START_</b> a <b>_END_</b> registros <br>TOTAL REGISTROS: <b>_TOTAL_</b> Registros</b>",
                        "sInfoEmpty": "Mostrando 0 A 0 registros",
                        "sInfoFiltered": "(Filtrados de un total de <b>_MAX_</b> registros)",
                        "sLoadingRecords": "CARGANDO...",
                        "sProcessing": "EN PROCESO...",
                        "sSearch": "Buscar:",
                        "sEmptyTable": "NO HAY INFORMACION DISPONIBLE PARA LA TABLA",
                        "oPaginate": {
                            "sFirst": "Inicio",
                            "sLast": "Fin",
                            "sNext": "Siguiente",
                            "sPrevious": "Anterior"
                        }
                    },
                    "aaSorting": [[0, "asc"]]'
                . '});'
                . '});'
                , 'text/javascript'
                , array('noescape' => true))
        ->prependFile('/josandro/public/js/sistema/cargo.js')
        ->prependFile('/josandro/public/js/datatables.scroller.min.js')
        ->prependFile('/josandro/public/js/responsive.bootstrap.js')
        ->prependFile('/josandro/public/js/dataTables.responsive.min.js')
        ->prependFile('/josandro/public/js/buttons.bootstrap.min.js')
        ->prependFile('/josandro/public/js/dataTables.buttons.min.js')
        ->prependFile('/josandro/public/js/dataTables.bootstrap.min.js')
        ->prependFile('/josandro/public/js/jquery.dataTables.min.js');
?>
<div class="page-title">
    <div class="title_left">
        <h3><i class="fa fa-file-text"></i> Cargos <small>PRINCIPAL</small></h3>
    </div>
    <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Buscar...">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button">IR!</button>
                </span>
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <hr>
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Registros del Sistema <small>Cargos</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>    
                        <button type="button" onclick="verAgregarCargo()" class="btn btn-success"><i class="fa fa-plus"></i> Registrar Cargo</button>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <p class="text-muted font-13 m-b-30">
                    A continuacion se listan todos las cargos registradas en el sistema.
                </p>
                <table id="tblCargo" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>CARGO</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($this->cargos as $cargo) {
                            echo '<tr>';
                            echo '<td>' . $cargo->getPk_cargo_id() . '</td>';
                            echo '<td>' . $cargo->getCargo() . '</td>';
                            echo '<td>';
                            echo '<a href="" onclick="verEditar(' . $cargo->getPk_cargo_id() . '); return false;" title="Editar este Cargo"><i class="fa fa-edit"></i></a>';
                            echo '&nbsp;&nbsp;';
                            echo '<a href="" onclick="verDetalle(' . $cargo->getPk_cargo_id() . '); return false;" title="Ver este Cargo a Detalle"><i class="fa fa-eye"></i></a>';
                            echo '</td>';
                            echo '</tr>';
                        }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalFormulario" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="overflow-y: scroll">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Formulario</h4>
            </div>
            <div class="modal-body">
                <div style="padding: 10px" class="container-fluid">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="x_panel">
                                <div class="x_content" id="divContenido"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <b>DOBLECLICK SOFTWARE E INGENIERIA S.A.S. &copy Copyright <?php echo date('Y'); ?></b>
            </div>
        </div>
    </div>
</div>

