<div class="clearfix"></div>
<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
<fieldset>
    <legend>ELIMINACIÓN DE PRODUCTO</legend>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="usuario">Encargado<span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input type="text" id="empleado" name="empleado" value="<?php echo $this->empleado; ?>" class="form-control" readonly>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="producto">Producto <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('producto')); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="cantidad">Cantidad<span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('cantidad')); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="ingreso">Ingreso<span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('ingreso')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="pendiente">Pendiente<span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('pendiente')); ?>
        </div>
    </div>

    <div hidden>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="idRegistro">Id Registro <span class="required">*</span></label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->formRow($form->get('idRegistro')); ?>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fechahorareg">Fecha de Ingreso <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('fechahorareg')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="proveedor">Proveedor <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('proveedor')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="telefono">Teléfono <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('telefono')); ?>
        </div>
    </div>
    <div class="ln_solid"></div>
    <fieldset>
        <legend>ESTADO DE PRODUCTO</legend>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="estado">Estado <span class="required">*</span></label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->formRow($form->get('estado')); ?>
            </div>
        </div>
    </fieldset>

    <div class="ln_solid"></div>
    <div class="form-group">
        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
            <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> ELIMINAR</button>
            <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-close"></i> CERRAR</button>

        </div>
    </div>

    <?php echo $this->form()->closeTag(); ?>