<div class="clearfix"></div>
<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
<fieldset>
    <legend>REGISTRO DE CONTRATO LABORAL</legend>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="encargado">Encargado<span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
           <input type="text" id="empleado" name="empleado" value="<?php echo $this->empleado; ?>" class="form-control" readonly>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="empleado">Empleado <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('empleado')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="identificacion">Identificación<span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('identificacion')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="telefono">Teléfono<span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('telefono')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="iniciocontrato">Inicio de Contrato<span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('iniciocontrato')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fincontrato">Fin de Contrato<span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('fincontrato')); ?>
        </div>
    </div>
    <div class="ln_solid"></div>
    <legend>ESTADO DE CONTRATO LABORAL</legend>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="estado">Estado <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('estado')); ?>
        </div>
    </div>
    <div hidden>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="idRegistro">Id Registro <span class="required">*</span></label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?php echo $this->formRow($form->get('idRegistro')); ?>
            </div>
        </div>
    </div>
    <div class="ln_solid"></div>
    <div class="form-group">
        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
            <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> GUARDAR</button>
            <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-close"></i> CERRAR</button>

        </div>
    </div>

    <?php echo $this->form()->closeTag(); ?>