<div class="clearfix"></div>
<?php
$form = $this->form;
$form->prepare();
$hiddenInfoRegistro = '';
echo $this->form()->openTag($form);
?>
<fieldset>
    <legend>Informacion del Pool</legend>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="idPool">ID <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('idPool')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Username <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('name')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="ranges">IPs <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('ranges')); ?>
        </div>
    </div>
</fieldset>
<div class="ln_solid"></div>
<div class="form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
        <button type="button" name="btnCancelar" class="btn btn-primary" data-dismiss="modal" value="Cerrar">Cerrar</button>
        <button type="submit" name="btnEnviar" class="btn btn-danger"><i class="fa fa-times"></i> Eliminar</button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
