<div class="clearfix"></div>
<form action="asignarsucursales" method="POST" onsubmit="return confirm('¿ DESEA GUARDAR LOS CAMBIOS REALIZADOS ?');">
    <fieldset>
        <legend>Asignacion de Sucursales</legend>
        <table id="tblIndex" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>SUCURSAL</th>
                    <th>ASIGNADA</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->sucursales as $sucursal) {
                    echo '<tr>';
                    echo '<td>' . $sucursal['idSucursal'] . '</td>';
                    echo '<td>' . $sucursal['sucursal'] . '</td>';
                    echo '<td>';
                    if (in_array($sucursal['idSucursal'], $this->sucursalesAsignadas)) {
                        echo '<input type="checkbox" name="asignadas[]" value="' . $sucursal['idSucursal'] . '" checked>';
                    } else {
                        echo '<input type="checkbox" name="asignadas[]" value="' . $sucursal['idSucursal'] . '">';
                    }
                    echo '</td>';
                    echo '</tr>';
                }
                ?>
            </tbody>
            <tfoot></tfoot>
        </table>
    </fieldset>
    <div class="ln_solid"></div>
    <input name="idUsuario" value="<?php echo $this->idUsuario; ?>" hidden>
    <div class="form-group">
        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
            <button type="button" name="btnCancelar" class="btn btn-danger" data-dismiss="modal" id="btnCancelar" value="Cerrar">Cerrar</button>
            <input type="submit" name="btnEnviar" class="btn btn-success" id="btnEnviar" value="Guardar">
        </div>
    </div>
</form>