<?php
$form = $this->formLogin;
$form->prepare();
$form->setAttribute('action', $this->url('login/default', array('controller' => 'login', 'action' => 'login')));
echo $this->form()->openTag($form);
?>

<h1 style="color: #dc901a"></h1>
<div>
    <input type="text" name="login" class="form-control" placeholder="Usuario" required>
</div>
<div>
    <input type="password" id="password" name="password" class="form-control" placeholder="Contraseña" required>
</div>
<div>
    <input type="submit" class="btn btn-default submit" value="Iniciar Sesion">
    <li><a href="/gimnasio/public/inicio.php">Recuperar Contraseña</a></li>
    <ul class="dropdown-menu dropdown-usermenu pull-right">
        
        <li><a href="<?php echo $this->url('login/default', array('controller' => 'login', 'action' => 'cerrarSesion')) ?>"><i class="fa fa-sign-out pull-right"></i> Salir</a></li>
    </ul>
</div>
<div class="clearfix"></div>
<div class="separator">
    <div class="clearfix"></div>
    <br />

</div>
<?php echo $this->formElement($form->get('security')) ?>
<?php echo $this->form()->closeTag() ?>
