<?php
$form = $this->form;
$form->prepare();
?>
<div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="tipocliente">Tipo Hotspot</label>
    <div class="col-md-6 col-sm-6 col-xs-12">
        <?php echo $this->formRow($form->get('tipohotspot')); ?>
    </div>
</div>
<div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="identificacion">Identificacion</label>
    <div class="col-md-6 col-sm-6 col-xs-12">
        <?php echo $this->formRow($form->get('identificacion')); ?>
    </div>
</div>
<?php if ($form->get('tipocliente')->getValue() == 'Persona Natural') { ?>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="nombres">Nombres</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('nombres')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="apellidos">Apellidos</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('apellidos')); ?>
        </div>
    </div>
<?php } else { ?>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="razonsocial">Razon Social</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('razonsocial')); ?>
        </div>
    </div>
<?php } ?>
