<?php
$form = $this->formPermisoLaboral;
$form->prepare();
$hiddenInfoRegistro = '';
$hiddenSeleccionar = '';
$action = $form->getAttribute('action');

if ($action == 'add') {
    $hiddenInfoRegistro = 'hidden';
}
if ($action == 'edit') {
    $hiddenSeleccionar = 'hidden';
}
if ($action == 'detail' || $action == 'delete' || $action == 'conceder' || $action == 'denegar') {
    $hiddenSeleccionar = 'hidden';
}
echo $this->form()->openTag($form);
?>


<fieldset>
    <legend>Informacion del Empleado</legend>
    <div class="form-group" hidden="true">                
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fk_empleado_id">ID Empleado *</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="form-group">                
                <?php echo $this->formRow($form->get('fk_empleado_id')); ?>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="empleado">Empleado *</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="form-group">                
                <?php echo $this->formRow($form->get('empleado')); ?>
            </div>
        </div>
    </div>  
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="identificacion">Identificacion *</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="form-group">                
                <?php echo $this->formRow($form->get('identificacion')); ?>
            </div>
        </div>
    </div>
</fieldset>
<hr>
<fieldset>
    <legend>Informacion del Permiso Laboral</legend>        
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="motivo">Motivo *</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="form-group">
                <?php echo $this->formRow($form->get('motivo')); ?>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fechapermiso">Fecha Permiso *</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="form-group">
                <?php echo $this->formRow($form->get('fechapermiso')); ?>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="dias">Dia(s) *</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="form-group">
                <?php echo $this->formRow($form->get('dias')); ?>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="horas">Hora(s) *</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="form-group">
                <?php echo $this->formRow($form->get('horas')); ?>
            </div>
        </div>
    </div>    
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="descripcion">Descripcion *</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="form-group">
                <?php echo $this->formRow($form->get('descripcion')); ?>
            </div>
        </div>
    </div>
    <div class="form-group" <?php echo $hiddenSeleccionar; ?>>
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="respaldo">Respaldo </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="form-group">
                <?php echo $this->formRow($form->get('respaldo')); ?>
            </div>
        </div>
    </div>
    <div class="form-group" <?php echo $hiddenInfoRegistro; ?>>
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="observacion">Observacion *</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="form-group">
                <?php echo $this->formRow($form->get('observacion')); ?>
            </div>
        </div>
    </div>
    <div class="form-group" <?php echo $hiddenInfoRegistro; ?>>
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="estado">Estado *</label>
        <div class="ccol-md-6 col-sm-6 col-xs-12">            
            <div class="form-group">
                <?php echo $this->formRow($form->get('estado')); ?>
            </div>
        </div>
    </div>   
    <div class="form-group" <?php echo $hiddenInfoRegistro; ?> align="center">
        <div class="form-group">            
            <a target="_blank" href="<?php echo $this->url('talentohumano/default', array('controller' => 'permiso-laboral', 'action' => 'descargar', 'id1' => $form->get('pk_permiso_id')->getValue(), 'id2' => $this->refresh )); ?>" class="btn btn-primary">Ver Respaldo</a>
        </div>
    </div>
    <div class="form-group" hidden>        
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="form-group">
                <input name="refresh" id="refresh" value="<?php echo $this->refresh ?>" class="form-control" readonly="true" hidden>
            </div>
        </div>
    </div>
</fieldset>
<hr>
<fieldset <?php echo $hiddenInfoRegistro; ?>>
    <legend>Informacion de Registro</legend>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="pk_permiso_id">ID Permiso Laboral </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('pk_permiso_id')); ?>
        </div>
    </div>      
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="registradopor">Registrado Por </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('registradopor')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fechahorareg">Fecha Registro </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('fechahorareg')); ?>
        </div>
    </div>    
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="modificadopor">Modificado Por </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('modificadopor')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fechahoramod">Fecha Modificacion </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('fechahoramod')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="confirmadopor">Confirmado Por </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('confirmadopor')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fechahoraconfirm">Fecha Confirmacion </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('fechahoraconfirm')); ?>
        </div>
    </div>
</fieldset>

<div class="ln_solid"></div>
<div class="form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
        <?php
        echo $this->formRow($form->get('btnCancelar'));
        if ($action != 'detail') {
            if ($action == 'edit') {
                echo $this->formSubmit($form->get('btnEnviar')->setValue('Editar'));
            } else if ($action == 'delete') {
                echo $this->formSubmit($form->get('btnEnviar')->setValue('Eliminar'));
            } else if ($action == 'conceder') {
                echo $this->formSubmit($form->get('btnEnviar')->setValue('Conceder'));
            } else if ($action == 'denegar') {
                echo $this->formSubmit($form->get('btnEnviar')->setValue('Denegar'));
            } else {
                echo $this->formSubmit($form->get('btnEnviar'));
            }
        }
        ?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
