<div class="clearfix"></div>
<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
<fieldset>
    <legend>Registro de Respuesta</legend>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="respuesta">Respuesta<span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('respuesta')); ?>
        </div>
    </div>


</fieldset>

<div class="form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
        <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> Guardar</button>
        <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-close"></i> Cerrar</button>
    </div>
</div>
<div hidden>
    <?php echo $this->formRow($form->get('idRespuesta')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>


